### ISSUE TITLE
uninitialized constant MSpecOptions::SummaryFormatter in ruby ci

### ISSUE THREAD

**Issue by znz** [ruby/mspec#18]
https://travis-ci.org/ruby/ruby/builds/160663397 failed at `make test-rubyspec MSPECOPT=-fm`.

```
$ make test-rubyspec MSPECOPT=-fm
generating x86_64-linux-fake.rb
x86_64-linux-fake.rb updated
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./spec/mspec/bin/mspec run -B ./spec/default.mspec -fm
ruby 2.4.0dev (2016-09-17 trunk 56179) [x86_64-linux]
/home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/options.rb:290:in `block in formatters': uninitialized constant MSpecOptions::SummaryFormatter (NameError)
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/options.rb:107:in `process'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/options.rb:147:in `parse'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/commands/mspec-run.rb:77:in `options'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:224:in `main'
	from /home/travis/build/ruby/ruby/spec/mspec/bin/mspec-run:7:in `<main>'
make: *** [test-rubyspec] Error 1
```

**Comment by eregon** [comment]
Thank you for the report!
I restarted the build, which should succeed now.
